config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

  resources :users
  resources :routines
  resources :products
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook_create'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :routineproducts
  has_many :routines, through: :routineproducts
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
  has_many :routineproducts
  has_many :products, through: :routineproducts

  # scope :favorited, -> { where(favorited: true) }

  # def self.favorited
  #   where(favorited: true)
  # end
end

# @user_favorited = Routine.favorited
 #activerecord scope method

app/models/routineproduct.rb
class Routineproduct < ApplicationRecord
  belongs_to :routine
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  has_many :routines
  after_initialize :set_defaults

    def set_defaults
      self.uid ||= "okay"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception

   def logged_in?
      current_user.id != nil
    end

    def current_user
   @user = (User.find_by(id: session[:user_id]) || User.new)
 end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @products = []
    5.times do
    @products << Product.new
    end
  end

  def create
    # @product = Product.create(product_params)
    if params.has_key?("product")
      Product.create(product_params(params["product"]))
    else
    params["products"].each do |product|
   if product["brand"] != "" || product["purpose"] != "" || product["shade"] != ""
     Product.create(product_params(product))
       end
  end
end
  redirect_to '/routines'

end

private
  def product_params(my_params)
    my_params.permit(:brand, :purpose, :shade)
    end
  end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  
  def index
    @routines = Routine.all
  end

  def new
    @routine = Routine.new
  end

  def create
    @routine = Routine.create(routine_params)
    @routine.save
    binding.pry
  
    redirect_to new_product_path
  end

  def update
    @routine = Routine.find_by(params[:id])
  end

private

  def routine_params
    params.require(:routine).permit(:category, :title, :step, :user_id)
  end

end

app/controllers/sessions_controller.rb
require 'pry'
class SessionsController < ApplicationController

  def new
  end

 #  def create
 #     user = User.find_by(username: params[:username])
 #   if user && user.authenticate(params[:password])
 #     session[:user_id] = user.id
 #     redirect_to user_path(user.id)
 #   else
 #    flash[:error] = "Sorry, we could not find the combination, try again or signup."
 #     redirect_to '/users/new'
 #   end
 # end

  def destroy
    session.clear
    redirect_to '/'
  end

#   def create
#   if user = User.find_by(username: params[:username])
#     user && user.authenticate(params[:password])
#       session[:user_id] = user.id
#       redirect_to user_path(user.id)
#   else
#      flash[:error] = "Sorry, we could not find the combination, try again or signup."
#       redirect_to '/users/new'
#     end
#   user = User.find_or_create_by(uid: auth['uid']) do |u|

#       u.name = auth['info']['name']
#       u.email = auth['info']['email']
#       u.image = auth['info']['image']
#     session[:user_id] = user.id
#     render 'users/show'
#   end
# end

def create
user = User.find_by(username: params[:username])
  if user && user.authenticate(params[:password])
    # session[:user_id] = user.id
    
    redirect_to user_path(user.id)
  else
   flash[:error]='Sorry, we could not find the combination, try again or signup.'
    redirect_to '/users/new'
  end
end

def facebook_create
  @user = User.find_or_create_by(uid: auth['uid']) do |u|
    u.name = auth['info']['name']
    u.email = auth['info']['email']
    u.image = auth['info']['image']
    u.uid = auth['uid']
  end

  session[:user_id] = @user.id

  render 'users/show'
end

#   user = User.find_or_create_by(uid: auth[‘uid’]) do |u|
#     binding.pry
#     u.name = auth[‘info’][‘name’]
#     u.email = auth[‘info’][‘email’]
#     u.image = auth[‘info’][‘image’]
#   end
#   session[:user_id] = user.id
#   render 'users/show'

# end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
    #want to show current users info.
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
    redirect_to user_path(@user)
  else
    flash[:error] = "Username has been used."
    redirect_to new_user_path
  end
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :full_name, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Routines to Remember</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1> Routines to Remember </h1>

      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/new.html.erb
<div class='appdesign'>
  <%=form_tag products_path do %>
<%@products.each do |product|%>
 <%= fields_for 'products[]', product do |p| %>
<div class="field">
       <%= p.label :brand%><br>
       <%= p.text_field :brand %>
     </div>
     <div class="field">
       <%= p.label :purpose %><br>
       <%= p.text_field :purpose%>
     </div>
     <div class="field">
       <%= p.label :shade %><br>
       <%= p.text_field :shade%>
     </div>

   <% end %>
<% end %>
  <div class="actions">
    <%= submit_tag %>
  </div>

</div>
<%end%>

app/views/routines/edit.html.erb
Edit Routine

app/views/routines/index.html.erb
list of all routines and being able to access and addd more products.
shows products for each routine

<%@routines.each do |routine|%>
<%=routine.name%>
<%=routine.products%>
<%end%>

app/views/routines/new.html.erb
<%=form_for @routine do |f|%>

<%= f.label :category %>
<%= f.text_field :category%><p>

  <%= f.label :title %>
  <%= f.text_field :title%><p>

    <%= f.label :step %>
    <%= text_area(:step, :text, size: "20x10")%><p>

    <%= f.submit "Add Products" %>
  <%end%>

app/views/users/home.html.erb
<div class=login>
<br><br>
<center>
<button><%=link_to 'Log In', login_path%></button><br>
<button><%=link_to 'Sign Up', new_user_path%></button><br>
<button><%= link_to('Log in with Facebook!', '/auth/facebook') %></button>
</center>
</div>

app/views/users/new.html.erb
<%=link_to 'Log In', login_path%>

<%=form_for @user do |f| %>

<%= f.label :username %>
<%= f.text_field :username%><p>

<%= f.label :full_name %>
<%= f.text_field :full_name%><p>

<%= f.label :password %>
<%= f.password_field :password%><p>

  <%= f.label :bio  %><br>
  <%= f.text_area :bio%><p>


<%= f.submit "Create User" %>
<%end%>

app/views/users/show.html.erb
<h2>Welcome <b><%=@user.name%></b> </h2>
<br>
Bio:<%=@user.bio%>
<br>

<%=link_to 'Routines', routines_path%>
<%=link_to 'Log Out', logout_path%>
<%=link_to 'Create a new Routine', new_routine_path%>